name = "demo"
description = "Demo of default and corner cases"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["unicode", "length"]

executables = ["demo"]

[[depends-on]]
umwi = "*"

[[pins]]
umwi = { path='..' }
